# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hum_value', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.CharField(max_length=250)),
                ('moi_value', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tem_value', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Waterlevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_value', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Watersensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_sensor', models.CharField(max_length=250)),
            ],
        ),
    ]
