# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='actuator_value',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
