# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_plant_latitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='longitude',
            field=models.CharField(default=80.025158, max_length=250),
            preserve_default=False,
        ),
    ]
