# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-21 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_plant_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantcondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moi_value', models.CharField(max_length=250)),
                ('actuator_value', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='plant',
            name='actuator_value',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='moi_value',
        ),
        migrations.AddField(
            model_name='plantcondition',
            name='plant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='plants.Plant'),
        ),
    ]
